### ISSUE TITLE
Cannot build Dockerfile

### ISSUE THREAD

**Issue by auzias** [Pamplemousse/xaviermaso.com#7]
### Objective
Update `Dockerfile` so a non-root user runs the application.

### Issue
Cannot build Docker image.  See error:
```
Step 11/13 : COPY dist /usr/src/app/dist
COPY failed: stat /var/lib/docker/tmp/docker-builder252464510/dist: no such file or directory
```

There is no file `dist` on the repo.

### Suggestion
Add the content of the dist directory

**Comment by Pamplemousse** [comment]
This is not an issue!
The provided `Dockerfile` is intended to run the application, not to build it from sources.

In the CI (travis), there is a build step before actual image building; This step is creating the necessary `/usr/src/app/` content. See https://github.com/Pamplemousse/xaviermaso.com/blob/master/.travis.yml .

If you want to build the image locally for testing purposes, run `npm run build`!
And, if you do not want to install a full NodeJS stack locally, you could use `pamplemousse/xaviermaso.com`, by prepending a `docker run...` before any npm script you need to run (as described in the `README`).

**Comment by auzias** [comment]
Oops, my bad, I rushed a bit too fast on this one
